{
  "$comment": "this is intentionally valid json in yaml",
  "packages": [
    "./packages/router-tree-map",
    "./packages/reflect-annotations",
    "./packages/core",
    "./packages/types",
    "./packages/http",
    "./packages/router",
    "./packages/ingress"
  ]
}
